import dogs2 from '../assets/dogs.jpg';
import cats2 from '../assets/cat2.jpg';
import rabbits2 from '../assets/rabbit.jpg';

const products = [
  // Original Products
  {
    id: 1,
    name: "Dog Toy",
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    category: "Dogs",
    image: dogs2,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Cat Scratcher",
    price: 19.99,
    originalPrice: 24.99,
    discount: 20,
    category: "Cats",
    image: cats2,
    rating: 4.7,
  },
  {
    id: 3,
    name: "Rabbit Hutch",
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    category: "Rabbits",
    image: rabbits2,
    rating: 4.6,
  },
  // Additional Products for Each Category
  ...Array.from({ length: 10 }, (_, i) => ({
    id: 4 + i,
    name: `Dog Collar ${i + 1}`,
    price: 15.99,
    originalPrice: 20.99,
    discount: 24,
    category: "Dogs",
    image: dogs2,
    rating: 4.3 + (i % 3) * 0.1, // Dynamic ratings
  })),
  ...Array.from({ length: 10 }, (_, i) => ({
    id: 14 + i,
    name: `Cat Tree ${i + 1}`,
    price: 45.99,
    originalPrice: 59.99,
    discount: 23,
    category: "Cats",
    image: cats2,
    rating: 4.4 + (i % 2) * 0.1,
  })),
  ...Array.from({ length: 10 }, (_, i) => ({
    id: 24 + i,
    name: `Rabbit Feeder ${i + 1}`,
    price: 25.99,
    originalPrice: 35.99,
    discount: 28,
    category: "Rabbits",
    image: rabbits2,
    rating: 4.5 + (i % 4) * 0.05,
  })),
  // More Specific Products for Diversity
  {
    id: 34,
    name: "Luxury Dog Bed",
    price: 89.99,
    originalPrice: 119.99,
    discount: 25,
    category: "Dogs",
    image: dogs2,
    rating: 4.8,
  },
  {
    id: 35,
    name: "Interactive Cat Laser",
    price: 12.99,
    originalPrice: 18.99,
    discount: 31,
    category: "Cats",
    image: cats2,
    rating: 4.9,
  },
  {
    id: 36,
    name: "Rabbit Playpen",
    price: 69.99,
    originalPrice: 99.99,
    discount: 30,
    category: "Rabbits",
    image: rabbits2,
    rating: 4.7,
  },
  {
    id: 37,
    name: "Chew Resistant Dog Leash",
    price: 22.99,
    originalPrice: 29.99,
    discount: 23,
    category: "Dogs",
    image: dogs2,
    rating: 4.6,
  },
  {
    id: 38,
    name: "Catnip Toys",
    price: 9.99,
    originalPrice: 14.99,
    discount: 33,
    category: "Cats",
    image: cats2,
    rating: 4.8,
  },
  {
    id: 39,
    name: "Rabbit Grooming Kit",
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    category: "Rabbits",
    image: rabbits2,
    rating: 4.7,
  },
  {
    id: 40,
    name: "Adjustable Dog Harness",
    price: 32.99,
    originalPrice: 45.99,
    discount: 28,
    category: "Dogs",
    image: dogs2,
    rating: 4.8,
  },
  {
    id: 41,
    name: "Luxury Cat Bed",
    price: 49.99,
    originalPrice: 65.99,
    discount: 24,
    category: "Cats",
    image: cats2,
    rating: 4.9,
  },
  {
    id: 42,
    name: "Rabbit Chew Toys",
    price: 14.99,
    originalPrice: 19.99,
    discount: 25,
    category: "Rabbits",
    image: rabbits2,
    rating: 4.6,
  },
  {
    id: 43,
    name: "Durable Dog Chew Toy",
    price: 19.99,
    originalPrice: 25.99,
    discount: 23,
    category: "Dogs",
    image: dogs2,
    rating: 4.7,
  },
];

const categories = [
  {
    name: "All",
    image: dogs2, 
  },
  {
    name: "Dogs",
    image: dogs2,
  },
  {
    name: "Cats",
    image: cats2,
  },
  {
    name: "Rabbits",
    image: rabbits2,
  },
];

export { products, categories };
